### PR TITLE
JIRA-XXXX. Added rspec to Gemfile, rspec setup. 

### PR DESCRIPTION
**Pull request by OKrain**
- [x] @mrJmek - зробити pull з майстеру щоб pull request став зеленим
- [x] @vovka

### CODE REVIEW

**Comment by brouhaha88** [comment]
Check the `Rakefile` , maybe it needs to push after the build according to [http://blog.codeship.com/codeship-code-coverage-coveralls/](url).

Then you need to add a rake task that pushes your coverage report as soon as your build is finished.
`require 'coveralls/rake/task'
Coveralls::RakeTask.new`

**Comment by mrJmek** [comment]
Не хвилюйтеся, усі гілки стали сірими, бо ми змерджили bootstrap гілку з master тому GitHub вимагає щоб ми зробили pull змін.

**Comment by vovka** [comment]
@OKrain please add JIRA ticket number and title to PR title. "LV-123. Jira title goes here."

**Comment by vovka** [comment]
Looks good to me

**Pull request merged**
