### PR TITLE
LR-161. Setup angularjs library

### PR DESCRIPTION
**Pull request by sergiy17**
- [ ] @vovka 
- [ ] @mrJmek 
- [ ] @anatoliiibrahimov

### CODE REVIEW

**Comment by vovka** [comment]
Add two more reviewers.

**Comment by mrJmek** [comment]
Branch name: feature/setup_angularjs ?

**Comment by sergiy17** [comment]
And in the same time you would like to fix omniauth callback bug?
- Yes . Here i took note of the bug from LR-177

**Comment by mrJmek** [comment]
If I hold this branch I would do next stuff:

1) just copy content of config/initializers/devise.rb from master to this branch
2) Fix this issue in bugfix/branch
3) at first merge branch with bugfix, next merge branch with that angular feature.

**Pull request closed without merging**
