### PR TITLE
setup Jasmine gem insteat of Jasmine-rails gem

### PR DESCRIPTION
**Pull request by brouhaha88**
### JIRA:
**Change Jsmine-rails gem to Jasmine gem**: http://ssu-jira.softserveinc.com/browse/LR-179

### Description:
Setup Jasmine gem insteat of Jasmine-rails gem

### Reminder:
If there is checkbox near your nickname, please:
* Check code and changes;
* Leave your comments, share your thoughts with others;
* If you don't have any comments/ideas, please check checkbox that everything is OK.
(If you are last reviewer, i'll be grateful if you inform merge duty responsible (Gitter, whatever), that he could megre branches)

- [x] @vovka 
- [x] @mrJmek 
- [x] @anatoliiibrahimov

### CODE REVIEW

**Comment by anatoliiibrahimov** [comment]
@brouhaha88 i think everything is ok , except this spaces(but it is not important)

**Comment by mrJmek** [comment]
Don't mention, this is comment just for me (to check if everything ok).

_To remove previous **jasmine-rails** gem:_
1) remove  **gem 'jasmine-rails'** from **Gemfile** - bundle install (to update Gemfile.lock)
2) remove **spec/javascripts/support/jasmine.yml**
3) remove **mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)** from routes.rb

To install new **jasmine** gem:
1) add **gem 'jasmine'** to **Gemfile** - bundle install (to update Gemfile.lock)
2) rails g jasmine:install and check next files:
>    exist  spec
>    identical  spec/javascripts/helpers/.gitkeep
>    identical  spec/javascripts/support/jasmine.yml
>    identical  spec/javascripts/support/jasmine_helper.rb
3) add **bundle exec rake jasmine:ci** to codeship

**Comment by vovka** [comment]
Why did you decide to rework it?

**Comment by mrJmek** [comment]
@vovka 
gem 'jasmine' - it's official gem from Jasmine developers http://jasmine.github.io/edge/ruby_gem.html
https://github.com/jasmine/jasmine-gem

And main problem, was that gem 'jasmin-rails' didn't start if javascript code contained:
`+$(document).ready(function() { });`
That's why we had problems with phantomjs during tests at codeship.

And **$(document).ready(function() { });** we need for turbolinks:
http://stackoverflow.com/questions/18770517/rails-4-how-to-use-document-ready-with-turbo-links

**Comment by vovka** [comment]
looks good

**Pull request merged**
